  
# Site settings

# NB! Set your site's url, otherwise stuff will break :)

url: "cs.utexas.edu"

# If you're hosting your site at a Project repository on GitHub pages
# (https://yourusername.github.io/repository-name)
# and NOT your user repository (https://yourusername.github.io)
# then add in the baseurl here, like this: "/repository-name"
#
# NB! Without this *nothing* will work, because it's used in every path :)

baseurl: "/~mps"

# Google tracking id

google-tracking-id: "UA-89498391-1"

# Forces https everywhere in your website, except when you serve it locally
# If you are not hosted on Github Pages, and your host doesn't support https
# then you should disable it

force-https: True

#############
# HTML Head #
#############

lang: "en"
author: "Michail Shaposhnikov"
title: "{ Michail Shaposhnikov }"
description: "Software Engineer. Photographer. Adventurer."
keywords: "shaposhnikov, michail, personal, ut, austin, computer science, internship"
favicon: "/img/favicon.ico"

################
# Header layout #
################

black-favicon: "/img/rocket.png"

background-img: "../img/bg.jpg"

##############################
# Dynamic Text on the Header #
##############################

dynamic-typing: True
shuffle: False # Shuffle the lines.
loop: False
loop-count: 0 # Set False for infinite loop, or set any number for finite loop.
type-speed: 40
start-delay: 200
delete-delay: 5000
lines: # You can add HTML Tags in the Text
  - text: "Software Engineer. Photographer. Adventurer."

me-img: "/img/me.jpg"

##############################
# Color the browser elements #
##############################
color-browser: "#000000"
apple-status-bar-style: "black"

################
# Web app mode #
################

web-app-mode: True

# Icons for Web App mode

icon-36p: "/img/web-app/icon-36p.png"
icon-48p: "/img/web-app/icon-48p.png"
icon-72p: "/img/web-app/icon-72p.png"
icon-96p: "/img/web-app/icon-96p.png"
icon-144p: "/img/web-app/icon-144p.png"
icon-192p: "/img/web-app/icon-192p.png"

########
# Blog #
########

enable-gesture-navigation: False

post-preview-words: 20

paginate: 7

email-share: True
fb-share: True
twitter-share: True
linkedin-share: True
reddit-share: True
google-plus-share: True
tumblr-share: True
pinterest-share: False
pocket-share: False
vkontakte-share: False

disqus-shortname: "mps-1"

syntax-highlight: True

############
# Timeline #
############

events:
  - image: "/img/timeline/utcs.jpg"
    date: "August 2016 - Today"
    description: "Studying Computer Science at UT Austin."
  - image: "/img/timeline/moved_to_texas.jpg"
    date: "August 2011"
    description: "Moved to Houston, Texas."
  - image: "/img/timeline/started_soccer.jpg"
    date: "January 2004"
    description: "Started playing soccer."

# First image of the Timeline

timeline-img: "/img/timeline/default.jpg"

###########
# Contact #
###########

email: "misha.shapo98@utexas.edu"
resume-url : "https://drive.google.com/open?id=0B1XZ0c96WHnhZkI5OXp5SHNucUk"

################
# Author Blurb #
################

# The author blurb goes underneath blog posts.
# This works best when your author blurb image has a transparent background, or matches your site background color.

# if the author_blurb is not set, then this feature is skipped
author_blurb: "My name is Michail Shaposhnikov. My friends call me Misha. I am a computer science student at the University of Texas at Austin. I love videography, computer science, soccer and everything in between."
author_blurb_image: "/img/me.jpg"

##################
# Social Buttons #
##################

social:
  - title: "facebook"
    url: "https://www.facebook.com/misha.shaposhnikov1"
  - title: "github"
    url: "https://github.com/MishaShapo"
  - title: "youtube"
    url: "https://www.youtube.com/channel/UCrpfycZsTFGa7Es2Qy1Q4fg"
  - title: "linkedin"
    url: "https://www.linkedin.com/in/michail-shaposhnikov-28701893?trk=hp-identity-photo"

############
# 404 page #
############

not-found-img: "/img/not_found.png"

##################
# GPG on Keybase #
##################

keybase-username: ""
keybase-in-social: False
keybase-in-footer: False

################################################################################

# NB! Tread carefully if you want to change the variables below this point!

# Sections shown in the index page

pages_list:
  About: 'about'
  Blog: 'latest-post'
  Timeline: 'timeline'
  Contact: 'contact'

# Exclusion list from the generated _site

exclude: ["LICENSE", "README.md", "CONTRIBUTING", "CONTRIBUTORS", "scripts"]

# Pagination path

paginate_path: "/blog/page:num/"


# Enable minification SASS

sass:
  style: compressed

gems:
  - jekyll-paginate
  - jemoji
